# Generated by Django 3.1.1 on 2020-09-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200927_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_add_book', 'Can add books'), ('can_delete_book', 'Can Delete Books'), ('can_edit_book', 'Can Edit Books'))},
        ),
    ]
